version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - myportfolio_dist:/usr/share/nginx/html

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=peiruchien1@gmail.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
      - myportfolio_dist:/usr/share/nginx/html:ro
    depends_on:
      - myportfolio

volumes:
  nginx_secrets:
  myportfolio_dist:
