# docker-compose.prod.yml
version: "3.8"

volumes:
  nginx_secrets:
  myportfolio_dist:
  pnpm_store:        # optional cache: speeds up builds

services:
  # One-shot builder that compiles Astro and writes dist/ into the shared volume
  builder:
    image: node:18-alpine
    working_dir: /src
    restart: "no"
    environment:
      - CI=true
    volumes:
      - .:/src                         # your repo
      - myportfolio_dist:/out          # where we'll put the built files
      - pnpm_store:/root/.local/share/pnpm/store/v3   # pnpm cache (optional)
    command: >
      sh -lc '
        apk add --no-cache git &&
        corepack enable &&
        corepack prepare pnpm@9 --activate &&
        pnpm install --frozen-lockfile &&
        pnpm build &&
        rm -rf /out/* &&
        cp -r dist/. /out/
      '

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=peiruchien1@gmail.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
      - myportfolio_dist:/usr/share/nginx/html:ro
    depends_on:
      builder:
        condition: service_completed_successfully
